#!/bin/sh

### BEGIN INIT INFO
# Provides:		standby-monitor.js
# Required-Start:	$remote-fs $syslog
# Required-Stop:	$remote-fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
### END INIT INFO

case "$1" in
	start)
		echo "Starting standby-monitor service"
		/root/pimtector-server/standby-monitor.js &
		;;
	stop)
		echo "Stopping standby-monitor service"
		pkill -f /root/pimtector-server/standby-monitor.js
		;;
	*)
		echo "Usage: /etc/init.d/standby-monitor {start|stop}"
		exit 1
		;;
esac

exit 0

